"""Synthetic recovery test for the parameter regression.

Plants three populations of heads whose statistic follows, exactly, the
stencil prediction, the cross-correlation prediction, and neither, then checks
that the fitted slope against the true generator is ~1 with ~0 intercept and
that the slope against the wrong generator is not.

Also exercises the failure the design tool exists to prevent: with three
parameter values the joint model is refit on data generated by one hypothesis
and shown to reproduce the condition means regardless, which is what makes the
saturation warning necessary rather than pedantic.

    python selftest.py
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from parameter_regression import fit_arm, _ols
from experimental_design import a_optimality

RNG = np.random.default_rng(0)
N_SEEDS, N_HEADS = 20, 4


def synth(rvals, true_source, noise, sources=("stencil", "xcorr")):
    """Heads whose measured statistic equals the true source's prediction."""
    pred = {
        # deliberately different functional forms of r
        "stencil": lambda r: -r,
        "xcorr": lambda r: -0.5 * np.tanh(3.0 * r),
    }
    rows = []
    for r in rvals:
        for seed in range(N_SEEDS):
            seed_effect = noise * RNG.normal()
            for h in range(N_HEADS):
                rec = {"pde": "lf", "r": r, "seed": seed, "layer": 0, "head": h,
                       "asymmetry": pred[true_source](r) + seed_effect
                                    + 0.3 * noise * RNG.normal(),
                       "label": "acf"}
                for s in sources:
                    rec[f"pred_{s}_asymmetry"] = pred[s](r)
                    rec[f"pred_{s}_centrality"] = np.nan
                rows.append(rec)
    return pd.DataFrame(rows)


def report(df, title):
    recs, dropped = fit_arm(df, "lf", "asymmetry", ["stencil", "xcorr"], 400, RNG)
    res = pd.DataFrame(recs)
    print(f"\n{title}")
    print(res[res.model.str.startswith("single")][
        ["model", "term", "coef", "ci_lo", "ci_hi", "r2_between"]
    ].round(3).to_string(index=False))
    joint = res[res.model == "joint"]
    if len(joint):
        print("joint:", ", ".join(
            f"{t}={c:.3f}" for t, c in zip(joint.term, joint.coef)),
            f"| resid df {int(joint.between_resid_df.iloc[0])}",
            f"| r2_between {joint.r2_between.iloc[0]:.4f}")
    return res


def main():
    three = [0.1, 0.25, 0.4]

    res_s = report(synth(three, "stencil", 0.02), "generated by STENCIL, 3 values")
    res_x = report(synth(three, "xcorr", 0.02), "generated by XCORR, 3 values")

    def slope(res, model):
        row = res[(res.model == model) & (res.term != "intercept")]
        return float(row["coef"].iloc[0]), float(row["r2_between"].iloc[0])

    b_ss, r2_ss = slope(res_s, "single_stencil")
    b_sx, _ = slope(res_s, "single_xcorr")
    b_xx, r2_xx = slope(res_x, "single_xcorr")
    b_xs, _ = slope(res_x, "single_stencil")

    print("\nrecovery")
    print(f"  stencil-generated: slope vs stencil {b_ss:.3f} (want ~1), "
          f"vs xcorr {b_sx:.3f}")
    print(f"  xcorr-generated:   slope vs xcorr   {b_xx:.3f} (want ~1), "
          f"vs stencil {b_xs:.3f}")

    assert abs(b_ss - 1) < 0.1, f"stencil slope {b_ss}"
    assert abs(b_xx - 1) < 0.1, f"xcorr slope {b_xx}"
    assert r2_ss > 0.99 and r2_xx > 0.99

    joint_r2 = [float(r[r.model == "joint"]["r2_between"].iloc[0])
                for r in (res_s, res_x)]
    print(f"\n  joint r2_between under both generators: "
          f"{joint_r2[0]:.6f}, {joint_r2[1]:.6f}")
    assert all(v > 1 - 1e-9 for v in joint_r2), "joint should be saturated at K=3"
    print("  both exactly 1.0, as expected: at 3 parameter values the joint fit "
          "is saturated and carries no evidence either way.")

    five = [0.1, 0.175, 0.25, 0.325, 0.4]
    res5 = report(synth(five, "stencil", 0.02), "generated by STENCIL, 5 values")
    j5 = float(res5[res5.model == "joint"]["r2_between"].iloc[0])
    df5 = int(res5[res5.model == "joint"]["between_resid_df"].iloc[0])
    print(f"\n  at 5 values: joint resid df {df5}, r2_between {j5:.6f} "
          "(now informative)")
    assert df5 > 0

    x3 = np.array([[-r, -0.5 * np.tanh(3 * r)] for r in three])
    x5 = np.array([[-r, -0.5 * np.tanh(3 * r)] for r in five])
    print(f"  A-optimality: 3 values {a_optimality(x3):.4g}, "
          f"5 values {a_optimality(x5):.4g}")
    print(f"  predictor correlation: 3 values {np.corrcoef(x3.T)[0,1]:+.4f}, "
          f"5 values {np.corrcoef(x5.T)[0,1]:+.4f}")

    print("\nself-test passed")


if __name__ == "__main__":
    main()
